### PR TITLE
Fix image, ssh key, apt

### PR DESCRIPTION
**Pull request by scarolan**
Three fixes:

Updates the Jenkins image to the latest available debian 9 version
FIxes the command for creating ssh key
Adds apt -y update before installing python

### CODE REVIEW

**Comment by scarolan** [comment]
I've tested this and made sure it runs start to finish in my google cloud shell, with default settings.

**Comment by scarolan** [comment]
Also thank you @aaron-lane for building this!  It's working great.

**Comment by scarolan** [comment]
I get some errors when I run the `make generate_docs` command.  Any tips?

```
sean_carolan@cloudshell:~/terraform-google-jenkins (stitch-vault)$ make generate_docs
docker run --rm -it \
        -v "/home/sean_carolan/terraform-google-jenkins":/workspace \
        gcr.io/cloud-foundation-cicd/cft/developer-tools-jenkins:0 \
        /bin/bash -c 'source /usr/local/bin/task_helper_functions.sh && generate_docs'
Generating markdown docs with terraform-docs
Working in . ...
2020/09/02 18:58:33 At 19:13: Unknown token: 19:13 IDENT local.jenkins_network_project_id
Warning! Exit code: 1
Working in ./examples/shared_vpc_example ...
2020/09/02 18:58:33 At 29:17: Unknown token: 29:17 IDENT var.project_id
Warning! Exit code: 1
Working in ./examples/simple_example ...
2020/09/02 18:58:33 At 18:13: Unknown token: 18:13 IDENT var.region
Warning! Exit code: 1
Working in ./modules/artifact_storage ...
2020/09/02 18:58:33 At 19:19: Unknown token: 19:19 IDENT var.bucket_name
Warning! Exit code: 1
Skipping ./test/fixtures/shared_vpc_example because README.md does not exist.
Skipping ./test/fixtures/simple_example because README.md does not exist.
Skipping ./test/setup because README.md does not exist.
```

**Comment by morgante** [comment]
Hmm if it's not working you can ignore for now. Looks like we might need to update the generation image.

**Comment by scarolan** [comment]
Ok, thanks.  I fixed the merge conflict.  Module's working great on our side.

**Review by morgante — APPROVED** [review]

**Pull request merged**
